foodmenuapp/food/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns=[
    path('',views.helloworld,name='helloworld'),
    path('allfood/',views.getAllItems,name='allfood'),
    path('<int:pk>/',views.details,name='details'),
    path('additem/',views.addItem,name='additem'),
    path('update/<int:pk>',views.updateItem,name='updateitem'),
    path('delete/<int:pk>',views.deleteItem,name='deleteitem')
]

foodmenuapp/foodmenuapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls'))
]

foodmenuapp/food/models.py
from django.db import models

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=1000,default='https://www.diabetesfoodhub.org/system/user_files/Images/1837-diabetic-pecan-crusted-chicken-breast_JulAug20DF_clean-simple_061720.jpg')

foodmenuapp/food/forms.py
from django.forms import ModelForm
from .models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
        #fields = ['item_name','item_desc','item_price','item_image']

foodmenuapp/food/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import Item
from django.template import loader
from .forms import ItemForm

# Create your views here.

def helloworld(request):
    
    return HttpResponse("hello world")

def getAllItems(request):
    item_list = Item.objects.all()
    #template = loader.get_template('food\index.html')
    return render(request,'food/index.html',{'item_list':item_list})

def details(request,pk):
    item = Item.objects.get(pk=pk)
    return render(request,'food/details.html',{'item':item})
    #return HttpResponse(f'Details page {pk}')

def addItem(request):
    item_form = ItemForm(request.POST or None)
    if item_form.is_valid():
        item_form.save()
        return redirect('food:allfood')
    return render(request,'food/create.html',{'item_form':item_form})

def updateItem(request,pk):
    item = Item.objects.get(pk=pk)
    item_form = ItemForm(request.POST or None, instance=item)
    if item_form.is_valid():
        item_form.save()
        return redirect('food:allfood')
    return render(request,'food/create.html',{'item_form':item_form})

def deleteItem(request,pk):
    item = Item.objects.get(pk=pk)
    if request.method == "POST":
        item.delete()
        return redirect('food:allfood')
    return render(request,'food/delete.html',{'item':item})

    

foodmenuapp/food/templates/food/create.html
{% extends 'food/menu.html' %} {% block content %}
<form method="POST">
  <h1>Add Item</h1>
  {% csrf_token %} {{item_form.as_p}}
  <button type="submit">Save</button>
</form>
{% endblock %}

foodmenuapp/food/templates/food/delete.html
<form method="POST">
  {% csrf_token %}
  <h1>Do you want to delete {{item.item_name}}</h1>
  <button type="submit">Yes</button>
</form>

foodmenuapp/food/templates/food/details.html
{% extends 'food/menu.html' %} {% block content %}
<div class="container">
  <div class="col-md-6">
    <img src="{{item.item_image}}" class="card" height="10%" />
  </div>
  <div class="col-md-6">
    <h1>Item name : {{item.item_name}}</h1>
    <h2>Item desc :{{item.item_desc}}</h2>
    <h2>Item Price : {{item.item_price}}</h2>
    <a href="{% url 'food:deleteitem' item.id %}">Delete</a>
  </div>
</div>

{% endblock %}

foodmenuapp/food/templates/food/index.html
{% extends 'food/menu.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    
  </head>
  <body>

    {% block content %}

    <h1 style="text-align: center;">Food</h1>
    <br>
    <p><ul>{% for item in item_list %} 
        
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img src="{{ item.item_image }} " alt = 'default food img' height="150px"> 
            </div>
            <div class="col-md-4">
                <p>{{item.item_name}}</p>
                <p>{{item.item_desc}}</p>
                <p>Rs.{{item.item_price}}</p>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:details' item.id%}" class="btn btn-warning">Details</a>
            </div>
        </div>
        <br>
        
            <!--<li>{{item.item_name}} ---
                <a href="{% url 'food:details' item.id%}"><button type="submit" >Details</button></a>
        </li> -->
        {%endfor%}</ul></p>
   {% endblock %}
  </body>
</html>

foodmenuapp/food/templates/food/menu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a href="#" class="navbar-brand">FoodApp</a>
      <div class="navbar">
        <a
          class="nav-item me-3 text-decoration-none"
          href="{% url 'food:allfood'  %}"
          >List Item</a
        >
        <a
          class="nav-item me-3 text-decoration-none"
          href="{% url 'food:additem'  %}"
          >Add Item</a
        >
        <a class="nav-item me-3 text-decoration-none" href="#">Update Item</a>
        <a class="nav-item me-3 text-decoration-none" href="#">Delete Item</a>
      </div>
    </nav>
    {% block content %} {% endblock %}
  </body>
</html>